# config.py
import os
from dotenv import load_dotenv

# 加载 .env 文件中的环境变量
load_dotenv()

# Telegram 机器人令牌

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_USER_ID = os.getenv("TELEGRAM_USER_ID")

# Notion API 密钥和数据库 ID
NOTION_API_KEY = os.getenv("NOTION_API_KEY")
NOTION_DATABASE_ID = os.getenv("NOTION_DATABASE_ID")
NOTION_DATABASE_ID_GROCERY = os.getenv("NOTION_DATABASE_ID_GROCERY")
NOTION_DATABASE_ID_RECIPES = os.getenv("NOTION_DATABASE_ID_RECIPES")

# OpenAI Project Key，用于调用 GPT-4o Vision 模型
OPENAI_PROJ_API_KEY = os.getenv("OPENAI_PROJ_API_KEY")
OPENAI_ASSISTANT_ID = os.getenv("OPENAI_ASSISTANT_ID")
OPENAI_ASSISTANT_ID_QUERY = os.getenv("OPENAI_ASSISTANT_ID_QUERY")
OPENAI_ASSISTANT_ID_PAIR = os.getenv("OPENAI_ASSISTANT_ID_PAIR")
OPENAI_ASSISTANT_ID_GROCERY = os.getenv("OPENAI_ASSISTANT_ID_GROCERY")
OPENAI_ASSISTANT_ID_COOK = os.getenv("OPENAI_ASSISTANT_ID_COOK")